Feature weatherjs
billodiallo/Weather-app pull request #1
Opened 2021-05-12 19:35 UTC by billodiallo

2021-05-13 02:37 UTC, rindrajosia requested changes
Changes Required :red_circle:
To Highlight: :angel:

- [ ] Good job by adding Necessary run common commands :+1:
- [ ] Webpack is well configured :100: 

To improve :factory_worker: [REQUIRED]:

- [x] As your readme file is the first thing that users check, I suggest that you use tools like grammarly in order to help you with your grammar.
- [ ] Your `live demo` and `issue` links are broken, It will be nice if you fix it.
- [ ] Your APP provides three different temperatures. Please precise which one is correct or add a label for each one.
![1](https://user-images.githubusercontent.com/58552748/118068924-e3596c00-b3ab-11eb-8860-1060f69a37cd.png)

- [ ] Please, keep all the styling logic in CSS files. (If you need to change something like a background image, add the classes with the different backgrounds to the CSS and then change the class name attribute with JavaScript) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/styling_requirement.png) from Pathwright)
- [ ] As you are using ES6 syntax, please use `arrow functions` instead of the `function keyword `([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/es6_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622983/))

Nice to have

- [ ]  it has a ‘loading’ component that displays from the time the form is submitted until the information comes back from the API ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/loading_component_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/weather-app))
- [ ]  it fetches the current geolocation of the user when the app is first accessed and fetches the weather from that location

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

2021-05-13 02:37 UTC, rindrajosia commented on src/modules/dom.js
> +  d.style.display = 'block';
Here for example you can create a `CSS Class` called ` .block`  in your `style.css` then you can add to `d`

2021-05-13 02:37 UTC, rindrajosia commented on src/modules/dom.js
> +  window.abc = function abc(data) {
Please use arrow function

2021-05-13 02:37 UTC, rindrajosia commented on src/modules/dom.js
> +    body.style.backgroundSize = 'cover';
Keep all the styling logic in CSS files

2021-05-14 12:24 UTC, billodiallo commented
Hi, TSEs,
change done
Thanks for the review.

2021-05-14 12:46 UTC, NtwaliHeritier approved these changes
### **STATUS: APPROVED✔✔✔✔**

Hello @billodiallo 
Great work making the required changes.

You can merge👍👌

Happy coding 💻💻💻

2021-05-14 14:03 UTC, merged